### ISSUE TITLE
Error after switching to HomeAssistant

### ISSUE THREAD

**Issue by SkytAsul** [RonFalafel/RSI#3]
Hello,
I just started using your util. When switching from WLED to HomeAssistant and clicking on Save in the settings menu, the program crashed and I cannot restart it. Here is the stacktrace:
```
Traceback (most recent call last):
  File "/home/skytasul/Softs/RSI/Main.py", line 19, in <module>
    settingsWindow = SettingsWindow(configurationManager, lightChangerResolver, yeeLightBulbFinder)
  File "/home/skytasul/Softs/RSI/Windows/SettingsWindow.py", line 14, in __init__
    self.lightChanger = self.lightChangerResolver.getLightChanger()
  File "/home/skytasul/Softs/RSI/Utils/LightChangerResolver.py", line 16, in getLightChanger
    return HALightChanger(home_assistant_ip, home_assistant_port)
  File "/home/skytasul/Softs/RSI/Utils/HALightChanger.py", line 10, in __init__
    self.rgbToHSVConverter = RGBToHSVConverter()
TypeError: 'module' object is not callable
```

**Comment by pierreski** [comment]
I think I can fix this by modifying the TypeError in HALightChanger by correcting RGBToHSVConverter import. Will create a Pull Request!

**Comment by RonFalafel** [comment]
Sorry for the delay, I have merged the Pull Request. Let me know if the issue persists.
